export interface TechStack {
  name: string;
  size?: { width: number; height: number };
  scale?: number;
  color: string;
}

export const techStack: TechStack[][] = [
  [
    // index 0
    { name: "Java", color: "#007396" },
    { name: "Spring Boot", color: "#6DB33F" },
    { name: "MySQL", color: "#4479A1" },
    { name: "Postman", color: "#FF6C37" },
    { name: "Git", color: "#F05032" },
  ],
  [
    // index 1
    {
      name: "Java",
      color: "#007396",
      scale: 1.05,
      size: { width: 50, height: 30 },
    },
    {
      name: "Spring Boot",
      color: "#6DB33F",
      scale: 1.05,
      size: { width: 100, height: 30 },
    },
    { name: "MySQL", color: "#4479A1" },
    { name: "Postman", color: "#FF6C37" },
    { name: "Git", color: "#F05032" },
    { name: "Spring Data JPA", color: "#6DB33F" },
    { name: "Mockito", color: "#6DB33F" },
    { name: "Cucumber", color: "#6DB33F" },
  ],
  [
    // index 2
    {
      name: "Java",
      color: "#007396",
      scale: 1,
      size: { width: 60, height: 35 },
    },
    {
      name: "Spring Boot",
      color: "#6DB33F",
      scale: 1,
      size: { width: 100, height: 35 },
    },
    { name: "MySQL", color: "#4479A1" },
    { name: "Postman", color: "#FF6C37" },
    { name: "Git", color: "#F05032" },
    { name: "Spring Data JPA", color: "#6DB33F" },
    { name: "Mockito", color: "#6DB33F" },
    { name: "Cucumber", color: "#6DB33F" },
    { name: "React", color: "#61DAFB" },
    { name: "TypeScript", color: "#3178C6" },
    { name: "CSS & HTML", color: "#E34F26" },
  ],
  [
    // index 3
    { name: "Java", color: "#007396", size: { width: 60, height: 35 } },
    { name: "Spring Boot", color: "#6DB33F", size: { width: 100, height: 35 } },
    { name: "MySQL", color: "#4479A1" },
    { name: "Postman", color: "#FF6C37" },
    { name: "Git", color: "#F05032" },
    { name: "Spring Data JPA", color: "#6DB33F" },
    { name: "Mockito", color: "#6DB33F" },
    { name: "Cucumber", color: "#6DB33F" },
    {
      name: "React",
      color: "#61DAFB",
      scale: 1.05,
      size: { width: 55, height: 30 },
    },
    {
      name: "TypeScript",
      color: "#3178C6",
      scale: 1.05,
      size: { width: 85, height: 30 },
    },
    {
      name: "CSS & HTML",
      color: "#E34F26",
      scale: 1.05,
      size: { width: 100, height: 30 },
    },
    {
      name: "Angular",
      color: "#DD0031",
    },
  ],
  [
    // index 4
    { name: "Java", color: "#007396", size: { width: 60, height: 35 } },
    { name: "Spring Boot", color: "#6DB33F", size: { width: 100, height: 35 } },
    { name: "MySQL", color: "#4479A1" },
    { name: "Postman", color: "#FF6C37" },
    { name: "Git", color: "#F05032" },
    { name: "Spring Data JPA", color: "#6DB33F" },
    { name: "Mockito", color: "#6DB33F" },
    { name: "Cucumber", color: "#6DB33F" },
    {
      name: "React",
      color: "#61DAFB",
      scale: 1,
      size: { width: 60, height: 35 },
    },
    {
      name: "TypeScript",
      color: "#3178C6",
      scale: 1,
      size: { width: 95, height: 35 },
    },
    {
      name: "CSS & HTML",
      color: "#E34F26",
      scale: 1,
      size: { width: 110, height: 35 },
    },
    {
      name: "Angular",
      color: "#DD0031",
      scale: 1.05,
      size: { width: 80, height: 30 },
    },
    { name: "RxJs", color: "#B7178C" },
  ],
  [
    // index 5
    { name: "Java", color: "#007396", size: { width: 60, height: 35 } },
    { name: "Spring Boot", color: "#6DB33F", size: { width: 100, height: 35 } },
    { name: "MySQL", color: "#4479A1" },
    { name: "Postman", color: "#FF6C37" },
    { name: "Git", color: "#F05032" },
    { name: "Spring Data JPA", color: "#6DB33F" },
    { name: "Mockito", color: "#6DB33F" },
    { name: "Cucumber", color: "#6DB33F" },
    { name: "React", color: "#61DAFB", size: { width: 60, height: 35 } },
    {
      name: "TypeScript",
      color: "#3178C6",
      scale: 1.05,
      size: { width: 95, height: 35 },
    },
    { name: "CSS & HTML", color: "#E34F26", size: { width: 110, height: 35 } },
    {
      name: "Angular",
      color: "#DD0031",
      scale: 1,
      size: { width: 90, height: 35 },
    },
    {
      name: "RxJs",
      color: "#B7178C",
      scale: 1.05,
      size: { width: 50, height: 30 },
    },
    { name: "MomentJS", color: "#FF6C37" },
  ],
  [
    // index 6
    { name: "Java", color: "#007396", size: { width: 60, height: 35 } },
    { name: "Spring Boot", color: "#6DB33F", size: { width: 100, height: 35 } },
    { name: "MySQL", color: "#4479A1" },
    { name: "Postman", color: "#FF6C37" },
    { name: "Git", color: "#F05032" },
    { name: "Spring Data JPA", color: "#6DB33F" },
    { name: "Mockito", color: "#6DB33F" },
    { name: "Cucumber", color: "#6DB33F" },
    { name: "React", color: "#61DAFB", size: { width: 60, height: 35 } },
    {
      name: "TypeScript",
      color: "#3178C6",
      scale: 1,
      size: { width: 105, height: 40 },
    },
    { name: "CSS & HTML", color: "#E34F26", size: { width: 110, height: 35 } },
    {
      name: "Angular",
      color: "#DD0031",
      scale: 1.05,
      size: { width: 95, height: 40 },
    },
    {
      name: "RxJs",
      color: "#B7178C",
      scale: 1,
      size: { width: 60, height: 35 },
    },
    { name: "MomentJS", color: "#FF6C37" },
    { name: "Node.js", color: "#339933" },
    { name: "AWS", color: "#FF9900" },
    { name: "Ag-Grid", color: "#FF6C37" },
  ],
  [
    // index 7
    { name: "Java", color: "#007396", size: { width: 60, height: 35 } },
    { name: "Spring Boot", color: "#6DB33F", size: { width: 100, height: 35 } },
    { name: "MySQL", color: "#4479A1" },
    { name: "Postman", color: "#FF6C37" },
    { name: "Git", color: "#F05032" },
    { name: "Spring Data JPA", color: "#6DB33F" },
    { name: "Mockito", color: "#6DB33F" },
    { name: "Cucumber", color: "#6DB33F" },
    { name: "React", color: "#61DAFB", size: { width: 60, height: 35 } },
    {
      name: "TypeScript",
      color: "#3178C6",
      scale: 1.05,
      size: { width: 105, height: 40 },
    },
    { name: "CSS & HTML", color: "#E34F26", size: { width: 110, height: 35 } },
    {
      name: "Angular",
      color: "#DD0031",
      scale: 1,
      size: { width: 105, height: 50 },
    },
    {
      name: "RxJs",
      color: "#B7178C",
      scale: 1.05,
      size: { width: 65, height: 35 },
    },
    { name: "MomentJS", color: "#FF6C37" },
    { name: "Node.js", color: "#339933" },
    { name: "AWS", color: "#FF9900" },
    { name: "Ag-Grid", color: "#FF6C37" },
    { name: "NgRx", color: "#B7178C" },
    { name: "Playwright", color: "#FF6C37" },
    { name: "Signal Store", color: "#B7178C" },
  ],
  [
    // index 8
    { name: "Java", color: "#007396", size: { width: 60, height: 35 } },
    { name: "Spring Boot", color: "#6DB33F", size: { width: 100, height: 35 } },
    { name: "MySQL", color: "#4479A1" },
    { name: "Postman", color: "#FF6C37" },
    { name: "Git", color: "#F05032" },
    { name: "Spring Data JPA", color: "#6DB33F" },
    { name: "Mockito", color: "#6DB33F" },
    { name: "Cucumber", color: "#6DB33F" },
    { name: "React", color: "#61DAFB", size: { width: 60, height: 35 } },
    {
      name: "TypeScript",
      color: "#3178C6",
      scale: 1,
      size: { width: 115, height: 45 },
    },
    { name: "CSS & HTML", color: "#E34F26", size: { width: 110, height: 35 } },
    {
      name: "Angular",
      color: "#DD0031",
      scale: 1.05,
      size: { width: 110, height: 55 },
    },
    {
      name: "RxJs",
      color: "#B7178C",
      scale: 1,
      size: { width: 80, height: 45 },
    },
    { name: "MomentJS", color: "#FF6C37" },
    { name: "Node.js", color: "#339933" },
    { name: "AWS", color: "#FF9900" },
    { name: "Ag-Grid", color: "#FF6C37" },
    { name: "NgRx", color: "#B7178C" },
    { name: "Playwright", color: "#FF6C37" },
    { name: "Signal Store", color: "#B7178C" },
    { name: "Chart.js", color: "#FF6C37" },
    { name: "Three.js", color: "#FF6C37" },
  ],
  [
    // index 9
    { name: "Java", color: "#007396", size: { width: 60, height: 35 } },
    { name: "Spring Boot", color: "#6DB33F", size: { width: 100, height: 35 } },
    { name: "MySQL", color: "#4479A1" },
    { name: "Postman", color: "#FF6C37" },
    { name: "Git", color: "#F05032" },
    { name: "Spring Data JPA", color: "#6DB33F" },
    { name: "Mockito", color: "#6DB33F" },
    { name: "Cucumber", color: "#6DB33F" },
    { name: "React", color: "#61DAFB", size: { width: 60, height: 35 } },
    {
      name: "TypeScript",
      color: "#3178C6",
      scale: 1.05,
      size: { width: 115, height: 45 },
    },
    { name: "CSS & HTML", color: "#E34F26", size: { width: 110, height: 35 } },
    {
      name: "Angular",
      color: "#DD0031",
      scale: 1,
      size: { width: 120, height: 60 },
    },
    { name: "RxJs", color: "#B7178C", size: { width: 80, height: 45 } },
    { name: "MomentJS", color: "#FF6C37" },
    { name: "Node.js", color: "#339933" },
    { name: "AWS", color: "#FF9900" },
    { name: "Ag-Grid", color: "#FF6C37" },
    { name: "NgRx", color: "#B7178C" },
    { name: "Playwright", color: "#FF6C37" },
    { name: "Signal Store", color: "#B7178C" },
    { name: "Chart.js", color: "#FF6C37" },
    { name: "Three.js", color: "#FF6C37" },
  ],
  [
    // index 10
    { name: "Java", color: "#007396", size: { width: 60, height: 35 } },
    { name: "Spring Boot", color: "#6DB33F", size: { width: 100, height: 35 } },
    { name: "MySQL", color: "#4479A1" },
    { name: "Postman", color: "#FF6C37" },
    { name: "Git", color: "#F05032" },
    { name: "Spring Data JPA", color: "#6DB33F" },
    { name: "Mockito", color: "#6DB33F" },
    { name: "Cucumber", color: "#6DB33F" },
    { name: "React", color: "#61DAFB", size: { width: 60, height: 35 } },
    {
      name: "TypeScript",
      color: "#3178C6",
      scale: 1,
      size: { width: 130, height: 60 },
    },
    { name: "CSS & HTML", color: "#E34F26", size: { width: 110, height: 35 } },
    {
      name: "Angular",
      color: "#DD0031",
      scale: 1.05,
      size: { width: 130, height: 65 },
    },
    { name: "RxJs", color: "#B7178C", size: { width: 80, height: 45 } },
    { name: "MomentJS", color: "#FF6C37" },
    { name: "Node.js", color: "#339933" },
    { name: "AWS", color: "#FF9900" },
    { name: "Ag-Grid", color: "#FF6C37" },
    { name: "NgRx", color: "#B7178C" },
    { name: "Playwright", color: "#FF6C37" },
    { name: "Signal Store", color: "#B7178C" },
    { name: "Chart.js", color: "#FF6C37" },
    { name: "Three.js", color: "#FF6C37" },
  ],
];
